In [ ]:
sentence_bn = [' আমরা আজ ল্যাব ক্লাস এ নিউরাল নেটওয়ার্ক  প্রয়োগ করব','আমাদের প্রোগ্রামিং অনেক ভালো লাগে' ,'আমরা সবাই এই  কোর্সে ভালো মার্ক পেতে চাই']
sentence_en = ['We do not know how to implement a neural network', 'We don\'t like programming t all','we are in great doubt about our marks in this course']


In [ ]:
import nltk
import warnings
warnings.filterwarnings("ignore")
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer()
# vec.fit(sentence_en)
model=vec.fit_transform(sentence_en)
vec.vocabulary_
vocab_list = vec.get_feature_names()
print(vocab_list)
# print(model.toarray())
count_list=model.toarray().sum(axis=0)

['about', 'all', 'are', 'course', 'do', 'don', 'doubt', 'great', 'how', 'implement', 'in', 'know', 'like', 'marks', 'network', 'neural', 'not', 'our', 'programming', 'this', 'to', 'we']


In [ ]:
print(dict(zip(vocab_list,count_list)))

{'about': 1, 'all': 1, 'are': 1, 'course': 1, 'do': 1, 'don': 1, 'doubt': 1, 'great': 1, 'how': 1, 'implement': 1, 'in': 2, 'know': 1, 'like': 1, 'marks': 1, 'network': 1, 'neural': 1, 'not': 1, 'our': 1, 'programming': 1, 'this': 1, 'to': 1, 'we': 3}


In [ ]:
from nltk import word_tokenize

vec_new = CountVectorizer(encoding='utf-8', tokenizer=word_tokenize)
vec_new.fit(sentence_bn)

vocab_list_bn = vec_new.get_feature_names()
print(vocab_list_bn)

['অনেক', 'আজ', 'আমরা', 'আমাদের', 'এ', 'এই', 'করব', 'কোর্সে', 'ক্লাস', 'চাই', 'নিউরাল', 'নেটওয়ার্ক', 'পেতে', 'প্রোগ্রামিং', 'প্রয়োগ', 'ভালো', 'মার্ক', 'লাগে', 'ল্যাব', 'সবাই']


In [ ]:
# Tokenazination
tokenized_bn = []

sentence_bn = sentence_bn + ['এইখানে আমরা নতুন আরো একটি বাক্য রাখলাম']

for sent in sentence_bn:
  tokenized_sent = word_tokenize(sent)
  tokenized_bn.append(tokenized_sent)

print(tokenized_bn)

[['আমরা', 'আজ', 'ল্যাব', 'ক্লাস', 'এ', 'নিউরাল', 'নেটওয়ার্ক', 'প্রয়োগ', 'করব'], ['আমাদের', 'প্রোগ্রামিং', 'অনেক', 'ভালো', 'লাগে'], ['আমরা', 'সবাই', 'এই', 'কোর্সে', 'ভালো', 'মার্ক', 'পেতে', 'চাই'], ['এইখানে', 'আমরা', 'নতুন', 'আরো', 'একটি', 'বাক্য', 'রাখলাম']]


In [ ]:
# Lab Task:
for x in vocab_list_bn:
  cnt=0
  for y in tokenized_bn:
    for z in y:
      if x==z:
        cnt+=1
  print(x+" occurs ",cnt," Times")

অনেক occurs  1  Times
আজ occurs  1  Times
আমরা occurs  3  Times
আমাদের occurs  1  Times
এ occurs  1  Times
এই occurs  1  Times
করব occurs  1  Times
কোর্সে occurs  1  Times
ক্লাস occurs  1  Times
চাই occurs  1  Times
নিউরাল occurs  1  Times
নেটওয়ার্ক occurs  1  Times
পেতে occurs  1  Times
প্রোগ্রামিং occurs  1  Times
প্রয়োগ occurs  1  Times
ভালো occurs  2  Times
মার্ক occurs  1  Times
লাগে occurs  1  Times
ল্যাব occurs  1  Times
সবাই occurs  1  Times


In [ ]:
# Manually Implement the Number of Occurences of each words in the sentence_bn dataset 

In [ ]:
from sklearn.preprocessing import LabelEncoder
std_names = ['জিয়াদ','নয়ন','কিশোর' ,'বিলাস' ,'ইমতিয়াজুল' ,'মনিরুল','নয়ন']

encoder = LabelEncoder()
name_labels = encoder.fit_transform(std_names)

# dense represnetation
print(name_labels)

[2 3 1 4 0 5 3]


In [ ]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()
name_labels = name_labels.reshape((7,1))

sparse_rep = encoder.fit_transform(name_labels).toarray()

print(sparse_rep)

[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]]
